uploads = []
generated = []

[[outputs]]
id = "Bi13TB5d8CMKiZJw2Pc0g"
uri = "file://GUIA-EDICION.md"
type = "text"
title = "Guía de Edición y Uso — Web CANVI"

[[outputs]]
id = "M03aHYxdQEFQgpMek88E_"
uri = "file://GUIA-DESPLIEGUE.md"
type = "text"
title = "Guía de Despliegue — Web CANVI"
